exports.seed = async function addProducts(knex) {
  const img = (seed) => `https://picsum.photos/seed/${seed}/400/500`;
  const sellerElectronics = knex.raw('(SELECT "sellerID" FROM sellers WHERE "shopName" = \'AHM Electronics\' LIMIT 1)');
  const sellerFashion = knex.raw('(SELECT "sellerID" FROM sellers WHERE "shopName" = \'AHM Fashion Hub\' LIMIT 1)');
  const category = (slug) => knex.raw('(SELECT "categoryID" FROM categories WHERE slug = ? LIMIT 1)', [slug]);

  const products = [
    {
      name: 'Samsung Galaxy A54 5G',
      description: '6.4" Super AMOLED display, 50MP camera, 5000mAh battery',
      price: 89999,
      discountPrice: 79999,
      discountPercentage: 11,
      stockQuantity: 45,
      seller_id: sellerElectronics,
      category_id: category('electronics'),
      sku: 'ELEC-A54',
      rating: 4.7,
      reviewCount: 128,
      imageUrl: img('galaxy-a54'),
      isActive: true,
    },
    {
      name: 'Wireless Earbuds Pro',
      description: 'Active noise cancellation, 30-hour battery life',
      price: 4999,
      discountPrice: 3999,
      discountPercentage: 20,
      stockQuantity: 120,
      seller_id: sellerElectronics,
      category_id: category('electronics'),
      sku: 'ELEC-EARBUDS',
      rating: 4.5,
      reviewCount: 89,
      imageUrl: img('earbuds-pro'),
      isActive: true,
    },
    {
      name: 'Smart Watch Series 5',
      description: 'Heart rate monitor, GPS, waterproof design',
      price: 12999,
      discountPrice: null,
      stockQuantity: 60,
      seller_id: sellerElectronics,
      category_id: category('electronics'),
      sku: 'ELEC-WATCH5',
      rating: 4.4,
      reviewCount: 56,
      imageUrl: img('smartwatch5'),
      isActive: true,
    },
    {
      name: 'Portable Bluetooth Speaker',
      description: '360° sound, 12-hour playtime, IPX7 waterproof',
      price: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      stockQuantity: 85,
      seller_id: sellerElectronics,
      category_id: category('electronics'),
      sku: 'ELEC-SPEAKER',
      rating: 4.3,
      reviewCount: 42,
      imageUrl: img('bt-speaker'),
      isActive: true,
    },
    {
      name: 'Men\'s Cotton Kurta',
      description: 'Premium cotton fabric, comfortable fit for all occasions',
      price: 2999,
      discountPrice: 2499,
      discountPercentage: 17,
      stockQuantity: 150,
      seller_id: sellerFashion,
      category_id: category('clothing'),
      sku: 'FASH-KURTA',
      rating: 4.6,
      reviewCount: 73,
      imageUrl: img('mens-kurta'),
      isActive: true,
    },
    {
      name: 'Women\'s Embroidered Shawl',
      description: 'Handcrafted embroidery, soft wool blend',
      price: 3499,
      discountPrice: null,
      stockQuantity: 80,
      seller_id: sellerFashion,
      category_id: category('clothing'),
      sku: 'FASH-SHAWL',
      rating: 4.8,
      reviewCount: 34,
      imageUrl: img('embroidered-shawl'),
      isActive: true,
    },
    {
      name: 'Classic Denim Jeans',
      description: 'Slim fit, stretch denim, multiple sizes available',
      price: 1999,
      discountPrice: 1599,
      discountPercentage: 20,
      stockQuantity: 200,
      seller_id: sellerFashion,
      category_id: category('clothing'),
      sku: 'FASH-JEANS',
      rating: 4.2,
      reviewCount: 95,
      imageUrl: img('denim-jeans'),
      isActive: true,
    },
    {
      name: 'Running Sneakers',
      description: 'Lightweight mesh upper, cushioned sole for comfort',
      price: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      stockQuantity: 75,
      seller_id: sellerFashion,
      category_id: category('clothing'),
      sku: 'FASH-SNEAKERS',
      rating: 4.5,
      reviewCount: 61,
      imageUrl: img('running-sneakers'),
      isActive: true,
    },
    {
      name: 'Leather Wallet',
      description: 'Genuine leather, multiple card slots, RFID protection',
      price: 1999,
      discountPrice: 1499,
      discountPercentage: 25,
      stockQuantity: 100,
      seller_id: sellerFashion,
      category_id: category('accessories'),
      sku: 'ACC-WALLET',
      rating: 4.4,
      reviewCount: 48,
      imageUrl: img('leather-wallet'),
      isActive: true,
    },
    {
      name: 'Stainless Steel Watch',
      description: 'Classic analog design, water resistant',
      price: 4499,
      discountPrice: null,
      stockQuantity: 55,
      seller_id: sellerFashion,
      category_id: category('accessories'),
      sku: 'ACC-WATCH',
      rating: 4.3,
      reviewCount: 29,
      imageUrl: img('steel-watch'),
      isActive: true,
    },
    {
      name: 'Non-Stick Cookware Set',
      description: '5-piece set with lids, PFOA-free coating',
      price: 8999,
      discountPrice: 7499,
      discountPercentage: 17,
      stockQuantity: 40,
      seller_id: sellerElectronics,
      category_id: category('home'),
      sku: 'HOME-COOKWARE',
      rating: 4.6,
      reviewCount: 67,
      imageUrl: img('cookware-set'),
      isActive: true,
    },
    {
      name: 'LED Desk Lamp',
      description: 'Adjustable brightness, USB charging port',
      price: 1499,
      discountPrice: null,
      stockQuantity: 90,
      seller_id: sellerElectronics,
      category_id: category('home'),
      sku: 'HOME-LAMP',
      rating: 4.1,
      reviewCount: 38,
      imageUrl: img('led-lamp'),
      isActive: true,
    },
    {
      name: 'Memory Foam Pillow',
      description: 'Orthopedic support, breathable cover',
      price: 999,
      discountPrice: 799,
      discountPercentage: 20,
      stockQuantity: 130,
      seller_id: sellerElectronics,
      category_id: category('home'),
      sku: 'HOME-PILLOW',
      rating: 4.0,
      reviewCount: 52,
      imageUrl: img('memory-pillow'),
      isActive: true,
    },
    {
      name: 'Skincare Essentials Kit',
      description: 'Cleanser, toner, moisturizer — complete daily routine',
      price: 4499,
      discountPrice: 3999,
      discountPercentage: 11,
      stockQuantity: 65,
      seller_id: sellerFashion,
      category_id: category('beauty'),
      sku: 'BEAU-SKINCARE',
      rating: 4.7,
      reviewCount: 84,
      imageUrl: img('skincare-kit'),
      isActive: true,
    },
    {
      name: 'Premium Perfume 50ml',
      description: 'Long-lasting fragrance, elegant packaging',
      price: 2999,
      discountPrice: null,
      stockQuantity: 70,
      seller_id: sellerFashion,
      category_id: category('beauty'),
      sku: 'BEAU-PERFUME',
      rating: 4.5,
      reviewCount: 41,
      imageUrl: img('perfume-50ml'),
      isActive: true,
    },
    {
      name: 'Yoga Mat Premium',
      description: 'Non-slip surface, 6mm thickness, carry strap included',
      price: 1299,
      discountPrice: 999,
      discountPercentage: 23,
      stockQuantity: 110,
      seller_id: sellerElectronics,
      category_id: category('sports'),
      sku: 'SPRT-YOGA',
      rating: 4.4,
      reviewCount: 36,
      imageUrl: img('yoga-mat'),
      isActive: true,
    },
    {
      name: 'Dumbbell Set 10kg',
      description: 'Adjustable weights, rubber-coated for floor protection',
      price: 4999,
      discountPrice: null,
      stockQuantity: 35,
      seller_id: sellerElectronics,
      category_id: category('sports'),
      sku: 'SPRT-DUMBBELL',
      rating: 4.6,
      reviewCount: 22,
      imageUrl: img('dumbbell-set'),
      isActive: true,
    },
    {
      name: 'Basmati Rice 5kg',
      description: 'Premium aged basmati, aromatic long grain',
      price: 1499,
      discountPrice: 1299,
      discountPercentage: 13,
      stockQuantity: 300,
      seller_id: sellerElectronics,
      category_id: category('groceries'),
      sku: 'GROC-RICE',
      rating: 4.8,
      reviewCount: 156,
      imageUrl: img('basmati-rice'),
      isActive: true,
    },
    {
      name: 'Cooking Oil 5L',
      description: '100% pure sunflower oil, cholesterol free',
      price: 1999,
      discountPrice: null,
      stockQuantity: 250,
      seller_id: sellerElectronics,
      category_id: category('groceries'),
      sku: 'GROC-OIL',
      rating: 4.5,
      reviewCount: 98,
      imageUrl: img('cooking-oil'),
      isActive: true,
    },
    {
      name: 'Building Blocks Set 500pcs',
      description: 'Creative construction toy, compatible bricks',
      price: 2499,
      discountPrice: 1999,
      discountPercentage: 20,
      stockQuantity: 80,
      seller_id: sellerFashion,
      category_id: category('toys'),
      sku: 'TOYS-BLOCKS',
      rating: 4.7,
      reviewCount: 45,
      imageUrl: img('building-blocks'),
      isActive: true,
    },
    {
      name: 'Remote Control Racing Car',
      description: 'High speed RC car, rechargeable battery included',
      price: 3499,
      discountPrice: 2999,
      discountPercentage: 14,
      stockQuantity: 50,
      seller_id: sellerFashion,
      category_id: category('toys'),
      sku: 'TOYS-RC-CAR',
      rating: 4.3,
      reviewCount: 31,
      imageUrl: img('rc-racing-car'),
      isActive: true,
    },
    {
      name: 'Pepsi Bottle',
      description: 'Refreshing carbonated drink available in multiple bottle sizes.',
      price: 140,
      discountPrice: 120,
      discountPercentage: 14,
      stockQuantity: 80,
      seller_id: sellerElectronics,
      category_id: category('groceries'),
      sku: 'GROC-PEPSI',
      rating: 4.6,
      reviewCount: 27,
      imageUrl: img('pepsi-bottle'),
      variants: JSON.stringify([
        { name: '345ML', label: '345ML', price: 120, stock_quantity: 30, sku: 'GROC-PEPSI-345' },
        { name: '500ML', label: '500ML', price: 160, stock_quantity: 25, sku: 'GROC-PEPSI-500' },
        { name: '1.5L', label: '1.5L', price: 260, stock_quantity: 25, sku: 'GROC-PEPSI-1500' },
      ]),
      isActive: true,
    },
    {
      name: 'Fresh Milk Bottle',
      description: 'Pure dairy milk available in family-friendly pack sizes.',
      price: 220,
      discountPrice: 200,
      discountPercentage: 9,
      stockQuantity: 60,
      seller_id: sellerElectronics,
      category_id: category('groceries'),
      sku: 'GROC-MILK',
      rating: 4.7,
      reviewCount: 19,
      imageUrl: img('fresh-milk'),
      variants: JSON.stringify([
        { name: '250ML', label: '250ML', price: 90, stock_quantity: 20, sku: 'GROC-MILK-250' },
        { name: '500ML', label: '500ML', price: 180, stock_quantity: 20, sku: 'GROC-MILK-500' },
        { name: '1L', label: '1L', price: 320, stock_quantity: 20, sku: 'GROC-MILK-1000' },
      ]),
      isActive: true,
    },
  ];

  const existingProducts = await knex('products').select('sku').whereIn('sku', products.map((product) => product.sku));
  const existingSkus = new Set(existingProducts.map((product) => product.sku));
  const newProducts = products.filter((product) => !existingSkus.has(product.sku));

  if (newProducts.length > 0) {
    await knex('products').insert(newProducts);
  }
};
